services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge